bernie-g/geckolib

- src/main/java/software/bernie/geckolib/animation/controller/EntityAnimationController.java
- src/main/java/software/bernie/geckolib/example/entity/EasingDemoEntity.java
- src/main/java/software/bernie/geckolib/file/AnimationFileLoader.java
- src/main/java/software/bernie/geckolib/util/AnimationUtils.java
- src/main/java/software/bernie/geckolib/util/json/JsonKeyFrameUtils.java
Replace string concatenation in logging statements with parameterized messages.
> Cleanup logging

- src/main/java/software/bernie/geckolib/animation/controller/EntityAnimationController.java
- src/main/java/software/bernie/geckolib/example/entity/EasingDemoEntity.java
- src/main/java/software/bernie/geckolib/file/AnimationFileLoader.java
- src/main/java/software/bernie/geckolib/util/AnimationUtils.java
- src/main/java/software/bernie/geckolib/util/json/JsonKeyFrameUtils.java
Replace string concatenation in logging statements with parameterized messages.
> Cleanup logging (again)

- gradle.properties
- src/main/java/software/bernie/geckolib/example/client/renderer/entity/ColorfulPigRenderer.java
- src/main/java/software/bernie/geckolib/example/entity/BrownEntity.java
- src/main/java/software/bernie/geckolib/example/entity/EasingDemoEntity.java
- src/main/java/software/bernie/geckolib/example/entity/EntityColorfulPig.java
- src/main/java/software/bernie/geckolib/example/entity/RobotEntity.java
- src/main/java/software/bernie/geckolib/util/AnimationUtils.java
> Update to 1.16.2

- src/main/java/software/bernie/geckolib/model/AnimatedGeoModel.java
- src/main/java/software/bernie/geckolib/molang/MolangRegistrar.java
-query.actor_count
-query.distance_from_camera
-query.health
-query.max_health
-query.yaw_speed
> Added initial molang queries

- src/main/java/software/bernie/geckolib/model/AnimatedGeoModel.java
- src/main/java/software/bernie/geckolib/molang/MolangRegistrar.java
- src/main/java/software/bernie/geckolib/util/MolangUtils.java
-query.is_in_water_or_rain
-query.is_in_water
-query.is_on_ground
-query.time_of_day
-query.is_on_fire
-query.ground_speed
> Implement new queries

- src/main/java/software/bernie/geckolib3/file/AnimationFile.java
- src/main/java/software/bernie/geckolib3/util/MatrixStack.java
As the title says, a fix and a new method addition to AnimationFile. I hope this method will get accepted, because otherwise, I'll have to use reflection, and that's not fun... 😖
> Scale normal fix and one addition to AnimationFile

- src/main/java/software/bernie/geckolib3/util/RenderUtils.java
Cocoloco is going to be happy on 1.15! 😄
> Fix quaternion rotation not working correctly with specific models

- src/main/java/software/bernie/geckolib3/geo/render/built/GeoQuad.java
For 1.15. That's the code I copied from `develop-1.12` branch.
> Fix UV mirroring with Box UVs (1.15)

- src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java
For 1.12.2. That's the code I copied from `develop` branch.
> Fix Box UV mirroring not working (1.12.2)

- src/main/java/software/bernie/geckolib3/renderer/geo/GeoItemRenderer.java
Credit to BaileyH for the fix, this is the Fabric version of the fix.
> Fixes Item lighting Fabric

- src/main/java/software/bernie/geckolib3/ArmorRenderingRegistryImpl.java
> Fixes `NullPointerException` crash.

- src/main/java/software/bernie/geckolib3/GeckoLib.java
Thanks to hydos for the mixin that showed me what to properly do.
> Fixes issue with Fabric API newer versions.

- src/main/java/software/bernie/geckolib3/renderer/geo/GeoEntityRenderer.java
- src/main/java/software/bernie/geckolib3/renderer/geo/GeoReplacedEntityRenderer.java
Will be setting up Forges soon for 1.15/1.16.
> Invisibility Fix for Fabric 

- src/main/java/software/bernie/geckolib3/renderers/geo/GeoItemRenderer.java
Credit to BaileyH for the fix.
> Fixes Item lighting 1.16

- src/main/java/software/bernie/geckolib3/renderers/geo/GeoItemRenderer.java
- src/main/java/software/bernie/geckolib3/util/GeckoLibUtil.java
fixed singleton animation sync
> removed singleton animation sync 1.15

- build.gradle
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
Also, only execute curseforge task when the key.properties is present.
> [1.15] Fix nameplate and lookvec debug orientation, nameplate condition

- build.gradle
- src/main/java/software/bernie/example/CommonListener.java
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
I also added the entity attributes which makes the example entites spawnable in the example mod.
> [1.16] Fix nameplate and lookvec debug orientation, nameplate condition 

- src/main/java/software/bernie/geckolib3/model/AnimatedGeoModel.java
This fixes various precision problems but requires an updated core(See https://github.com/bernie-g/geckolib-core/pull/3).
> [1.16] Switch to double precision to fix random stuttering. Implement pause.

- src/main/java/software/bernie/geckolib3/model/AnimatedGeoModel.java
This fixes various precision problems but requires an updated core(See https://github.com/bernie-g/geckolib-core/pull/3).
> [fabric/1.16] Switch to double precision to fix random stuttering. Implement pause

- src/main/java/software/bernie/geckolib3/model/AnimatedGeoModel.java
This fixes various precision problems but requires an updated core(See https://github.com/bernie-g/geckolib-core/pull/3).
> [1.15] Switch to double precision to fix random stuttering. Implement pause.

- src/main/java/software/bernie/geckolib3/renderer/geo/GeoBlockRenderer.java
Enable block entity renderer rotation on fabric
> Fix block entity rotation

- src/main/java/software/bernie/geckolib3/renderer/geo/GeoItemRenderer.java
Fixes the item GUI light in fabric
> Fix item GUI light

- src/main/java/software/bernie/geckolib3/renderer/geo/GeoBlockRenderer.java
- src/main/java/software/bernie/geckolib3/resource/GeckoLibCache.java
The block models were animating incorrectly when changing models on fabric.
> Fix incorrect block model rendering.

- src/main/java/software/bernie/example/ClientListener.java
- src/main/java/software/bernie/example/item/JackInTheBoxItem.java
- src/main/java/software/bernie/geckolib3/network/GeckoLibNetwork.java
- src/main/java/software/bernie/geckolib3/network/messages/S2CSyncAnimationMsg.java
Initial porting of animation syncing so that animations are played for other clients on a dedicated server.
> initial packets

- src/main/java/software/bernie/geckolib3/renderers/geo/GeoProjectilesRenderer.java
The green and blue color render were switched and I just switched them back.
> Fixed switched green and blue colors

- build.gradle
- src/main/java/software/bernie/geckolib3/file/GeoModelLoader.java
- src/main/java/software/bernie/geckolib3/geo/render/GeoBuilder.java
- src/main/java/software/bernie/geckolib3/geo/render/IGeoBuilder.java
- src/main/java/software/bernie/geckolib3/geo/render/built/GeoBone.java
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoBlockRenderer.java
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoItemRenderer.java
- Changed the forge maven repository to the new one.
- Added the cast (IAnimatableModel) for the GeoBlockRenderer and GeoItemRenderer.
- Added IGeoBuilder & related stuff
> Introduced IGeoBuilder for 1.12.2. & small fixes.

- src/main/java/software/bernie/example/entity/GeoExampleEntity.java
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
- Removed some code in the ExapleEntity (old animation used when rain)
> Entities playing the same animation fix

- src/main/java/software/bernie/example/client/renderer/entity/ExampleExtendedRendererEntityRenderer.java
- src/main/java/software/bernie/geckolib3/renderers/geo/ExtendedGeoEntityRenderer.java
basically some refactoring in the renderer. Also moved the check for if a bone is a armor bone to a abstract method. And changed access to the renderCycle field to setters and getters cause i need that for one of my mods
> Refactoring and improvement of extendedEntityRenderer

- src/main/java/software/bernie/example/client/renderer/entity/ExampleExtendedRendererEntityRenderer.java
- src/main/java/software/bernie/example/entity/ExtendedRendererEntity.java
- src/main/java/software/bernie/example/item/PotatoArmorItem.java
- src/main/java/software/bernie/geckolib3/item/GeoArmorItem.java
- src/main/java/software/bernie/geckolib3/renderers/geo/ExtendedGeoEntityRenderer.java
- src/main/java/software/bernie/geckolib3/renderers/geo/GeoArmorRenderer.java
- src/main/java/software/bernie/geckolib3/renderers/geo/IGeoRenderer.java
(Player) heads get renderered automatically too now
Geo Armor partially works now, it does not perfectly work yet but it is a beginning. 
Open points:
- limbs don't copy rotations properly
- animations on the armor don't work yet
> Head rendering support and WIP geo armor support

- Forge/core/src/main/java/software/bernie/geckolib3/core/manager/AnimationFactory.java
- Forge/src/main/java/software/bernie/geckolib3/file/AnimationFile.java
- Forge/src/main/java/software/bernie/geckolib3/geo/raw/tree/RawBoneGroup.java
- Forge/src/main/java/software/bernie/geckolib3/geo/raw/tree/RawGeometryTree.java
- Forge/src/main/java/software/bernie/geckolib3/geo/render/built/GeoBone.java
- Forge/src/main/java/software/bernie/geckolib3/geo/render/built/GeoModel.java
- Forge/src/main/java/software/bernie/geckolib3/network/GeckoLibNetwork.java
- Forge/src/main/java/software/bernie/geckolib3/renderers/geo/ExtendedGeoEntityRenderer.java
- Forge/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
- Forge/src/main/java/software/bernie/geckolib3/renderers/geo/GeoReplacedEntityRenderer.java
- Forge/src/main/java/software/bernie/geckolib3/resource/GeckoLibCache.java
- Forge/src/main/java/software/bernie/geckolib3/util/json/JsonKeyFrameUtils.java
Did not touch core code as I wasn't sure if FastUtil was being avoided there
> Move to FastUtil collections for consistency and efficiency.

- Forge/core/src/main/java/software/bernie/geckolib3/core/builder/AnimationBuilder.java
- Forge/core/src/main/java/software/bernie/geckolib3/core/builder/RawAnimation.java
- Forge/core/src/main/java/software/bernie/geckolib3/core/manager/AnimationFactory.java
- Forge/core/src/main/java/software/bernie/geckolib3/core/molang/MolangParser.java
- Forge/src/main/java/software/bernie/geckolib3/renderers/geo/GeoArmorRenderer.java
- Forge/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
Tiny one this one, just to fix the breaking change I inadvertently made in one of the earlier PRs
Please push new version after this merge so that it's a public release
> Fix the previous breaking change

- Fabric/src/main/resources/fabric.mod.json
> Add modmenu library badge

- common/src/main/java/software/bernie/geckolib/animation/EasingType.java
- common/src/main/java/software/bernie/geckolib/loading/json/typeadapter/BakedAnimationsAdapter.java
Currently not playtested to the extent that it should be so I made this a draft
Bedrock animations should now be loaded exactly the way they look in Blockbench
All the artists I know CRAVE this addition
Let me know if you are up to merge this when it's ready or if the code is too messy for your taste
> Full bedrock animation support
