src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java, src/main/java/software/bernie/geckolib3/renderers/geo/IGeoRenderer.java
This one fixes the same thing with box UV as `1.12.2` pull request (#56), however, it also fixes shading on the models incorrectly due to them being inverted in the positive direction. This is only needed when the cube is `0` size on any axis, I just added additional checks.
=> Fix BoxUV models have bottom face flipped vertically (1.15) and fix normals

src/main/java/software/bernie/geckolib3/renderers/geo/GeoArmorRenderer.java, src/main/resources/assets/geckolib3/geo/potato_armor.geo.json
Armor anchor points rework, @grillo78 asked me to take a look at it, and honestly the armor implementation was a mess. The scaling on swing, and other stuff are pretty much ugly hacks. Here is a better version, however here are a couple of condition that must be followed in order for the model to appear correctly:
* The armor anchor points should be:
* `0, 24, 0` for `helmet`
* `0, 24, 0` for `chestplate`
* `6, 22, 0` for `rightArm`
* `-6, 24, 0` for `leftArm`
* `2, 12, 0` for `rightBoot` and `rightLeg`
* `-2, 12, 0` for `leftBoot` and `leftLeg`
These changes were applied to potato armor which appears now correctly on top of Steve character. I haven't tested on Alex, but it should apply correctly there as well (and even take in account the arms being lower and closer to the body, I …
=> Fix armor anchors

src/main/resources/assets/geckolib3/geo/potato_armor.geo.json
Apparently, I was wrong about armor anchor points. I suppose Mojang changed the anchor point from `6` to `5` somewhere after `1.13`. So there are new anchor points needed for armors:
* The armor anchor points should be:
* `0, 24, 0` for `helmet`
* `0, 24, 0` for `chestplate`
* `5, 22, 0` for `rightArm` (instead of `-5`)
* `-5, 24, 0` for `leftArm` (instead of `-6`)
* `2, 12, 0` for `rightBoot` and `rightLeg`
* `-2, 12, 0` for `leftBoot` and `leftLeg`
=> [1.15] Fix armor model anchor (again)

src/main/resources/assets/geckolib3/geo/potato_armor.geo.json
Apparently, I was wrong about armor anchor points. I suppose Mojang changed the anchor point from `6` to `5` somewhere after `1.13`. So there are new anchor points needed for armors:
* The armor anchor points should be:
* `0, 24, 0` for `helmet`
* `0, 24, 0` for `chestplate`
* `5, 22, 0` for `rightArm` (instead of `-5`)
* `-5, 24, 0` for `leftArm` (instead of `-6`)
* `2, 12, 0` for `rightBoot` and `rightLeg`
* `-2, 12, 0` for `leftBoot` and `leftLeg`
This is the same thing as #77 but for `1.16`.
=> [1.16] Fix armor model anchor (again)

src/main/java/software/bernie/geckolib3/renderers/geo/GeoLayerRenderer.java
Trying to use the methods in GeoLayerRenderer I found that they were still using java models, this makes it impossible to use renderCopyModel or renderModel with geo models.
This PR changes the Entity Models to a Geo Provider making them possible to use.
_Screenshot from testing_
=> Updated GeoLayer to no longer use java models

src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java, src/main/java/software/bernie/geckolib3/renderer/geo/IGeoRenderer.java
This fixes the normal of the bottom face facing upwards(which messes up backface culling) and flips the bottom texture vertically by flipping the uv region endpoints(top left and bottom right).
=> [fabric/1.16] Fix bottom face being flipped in BoxUV, re-enable culling.

src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java, src/main/java/software/bernie/geckolib3/renderers/geo/IGeoRenderer.java
This fixes the normal of the bottom face facing upwards(which messes up backface culling) and flips the bottom texture vertically by flipping the uv region endpoints(top left and bottom right).
=> [1.15] Fix bottom face being flipped in BoxUV, re-enable culling.

src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java, src/main/java/software/bernie/geckolib3/renderers/geo/IGeoRenderer.java
This fixes the normal of the bottom face facing upwards(which messes up backface culling) and flips the bottom texture vertically by flipping the uv region endpoints(top left and bottom right).
=> [1.16] Fix bottom face being flipped in BoxUV, re-enable culling.

src/main/java/software/bernie/geckolib3/renderers/geo/GeoBlockRenderer.java
As you can see in khronos manual https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glMultiTexCoord.xml GLenum target SHOULD be "one of GL_TEXTUREi, where i ranges from 0 to GL_MAX_TEXTURE_COORDS - 1", not texture type. That cause performance drops and "gl invalid value" spam in log on some gpu's, my PR fix that.
=> Fix wrong glMultitexCoord target

src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java, src/main/java/software/bernie/geckolib3/renderers/geo/GeoReplacedEntityRenderer.java
Only appears to be an issue with GeoEntityRenderer and GeoReplacedEntityRenderer, other renderers are fine.
=> Fix renderColor's blue/green being flipped

src/main/java/software/bernie/geckolib3/item/GeoArmorItem.java, src/main/java/software/bernie/geckolib3/renderers/geo/GeoArmorRenderer.java
- Made `setCurrentItem` use the builder pattern, making it more consistent with other methods.
- Also altered GeoArmorItem to reflect this change.
- Bone names can now be set to null, wherein they will no longer have their state modified.
- This is useful for armor that doesn't use the entire set (e.g. helmet-only armor), so that modelers don't have to make any empty bones.
- `getRenderer` now throws an exception if the returning renderer is null to help with debugging.
- Removed try-catch-rethrow blocks in a couple areas since they were out of scope (would never trigger) and because the model provider's `getBone` method throws a similar exception anyways.
- Made `fitToBiped` protected to make it overridable.
I feel like a lot could still be cleaned up with `GeoArmorRenderer`, but I just …
=> Improve GeoArmorRenderer

build.gradle, src/main/java/software/bernie/example/GeckoLibMod.java, src/main/java/software/bernie/example/item/JackInTheBoxItem.java, src/main/java/software/bernie/geckolib3/network/GeckoLibNetwork.java, src/main/java/software/bernie/geckolib3/network/ISyncable.java, src/main/java/software/bernie/geckolib3/network/messages/SyncAnimationMsg.java, src/main/java/software/bernie/geckolib3/renderers/geo/GeoItemRenderer.java, src/main/java/software/bernie/geckolib3/util/GeckoLibUtil.java
This allows modders to make their items, blocks, etc. automatically synced on the network.
To do so, objects should implement `ISyncable` and call `GeckoLibNetwork.registerSyncable(this);` in their constructor.
Then, simply call `GeckoLibNetwork#syncAnimation` on the server whenever the animation state changes. Clients that receive this packet will then automatically invoke `ISyncable#onAnimationSync`.
See `JackInTheBoxItem` for an example.
You'll note that the `SYNCABLES` map uses `Supplier<ISyncable>` values. This is because Forge prefers people to store items, blocks, etc. using their delegates (see `registerSyncable`) since they can technically change at runtime? It's strange, but I designed the system around it.
For Fabric, this could probably be entirely tossed out and just use a …
=> Add basic ISyncable system

src/main/java/software/bernie/geckolib3/GeckoLib.java
There is no need to register a packets every time the mods are initialized
=> Network one-time initialization

gradle.properties, src/main/java/software/bernie/example/registry/RegistryUtils.java, src/main/java/software/bernie/geckolib3/GeckoLib.java, src/main/java/software/bernie/geckolib3/geo/render/GeoBuilder.java, src/main/java/software/bernie/geckolib3/geo/render/built/GeoCube.java, src/main/java/software/bernie/geckolib3/geo/render/built/GeoQuad.java, src/main/java/software/bernie/geckolib3/geo/render/built/GeoVertex.java, src/main/java/software/bernie/geckolib3/renderer/geo/GeoBlockRenderer.java, src/main/java/software/bernie/geckolib3/renderer/geo/GeoEntityRenderer.java, src/main/java/software/bernie/geckolib3/renderer/geo/GeoProjectilesRenderer.java, src/main/java/software/bernie/geckolib3/renderer/geo/GeoReplacedEntityRenderer.java, src/main/java/software/bernie/geckolib3/renderer/geo/IGeoRenderer.java, src/main/java/software/bernie/geckolib3/resource/GeckoLibCache.java, src/main/java/software/bernie/geckolib3/util/RenderUtils.java, src/main/java/software/bernie/geckolib3/util/VectorUtils.java, src/main/java/software/bernie/geckolib3/world/storage/GeckoLibIdTracker.java
Making GeckoLib compatible with these versions:
**yarn_mappings** 1.16.5+build.3 => 1.16.5+build.10
**loader_version** 0.11.1 => 0.11.6
**fabric_version** 0.29.4+1.16 => 0.36.0+1.16
The main changes here are name changes, specifically Vector3f to Vec3f, MaterialColor to MapColor, CompoundTag to NbtCompound and ResourceReloadListener.Synchronizer to ResourceReloader.Synchronizer. This pr will ensure [AbstractMethodError](https://github.com/bernie-g/geckolib/issues/148) won't be an issue. 
Note, I didn't bump the version in gradle.properties. I presume you will do it if this pr gets accepted.
=> Fix name refactoring issues causing AbstractMethodError 

src/main/java/software/bernie/example/CommonListener.java
Currently sometimes `FMLEnvironment` and sometimes `FMLLoader` is used to test whether running in production.
However `FMLEnvironment.production` can also be set to true when the system property `production` is set. With this, it's possible to simulate production in a development environment. Currently setting this system property when GeckloLib is installed will crash with:
```
java.lang.NullPointerException: Registry Object not present: geckolib3:bikeentity
at java.util.Objects.requireNonNull(Objects.java:290)
at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
at software.bernie.example.CommonListener.registerEntityAttributes(CommonListener.java:17
```
This pull request changes this to always use `FMLEnvironment` so it is possible to use the production system property …
=> Use FMLEnvironment instead of FMLLoader to determine whether running in production

src/main/java/software/bernie/geckolib3/renderers/geo/GeoLayerRenderer.java
The getter makes it easier to access the renderer to render model copies with different render types without having to use AnimationUtils.
=> Added a public getter to the geo layer renderer

src/main/java/software/bernie/geckolib3/renderers/geo/GeoLayerRenderer.java
Removes the unnecessary use of static methods for the class. This allows using getRenderer() to directly access the entity renderer and avoid abusive use of animation utils.
=> GeoLayerRenderer cleanup

build.gradle
**Versions:** all Fabric branches, specifically 1.17 
---
**Issue**
Geckolib currently only publishes a `dev` and `sources` jar. This means it is not possible to `include` Geckolib in a project because the only jar you can pull from the Geckolib repository is one with yarn-mapped names<sup>1</sup>. 
_Example of mapped code inside the jar_
_Crash when using a mod that includes Geckolib_
---
**Solution**
By adding a `remapJar` artifact to Geckolib's publications block, a non-dev (& non-mapped) jar will be published alongside the development jar:
*Example of the same code now properly unmapped*
*Geckolib being run in a production client as an `included` library*:
---
<sup>1This assumes you actually want to allow people to include Geckolib. Some people don't like it because it adds bloat to …
=> Add standard non-dev jar to publishing artifacts

build.gradle
In its current state, adding Geckolib on Fabric as a `modImplementation` dependency from the cloudsmith dependency only works with Yarn mappings. This means using Parchment/Mojmaps is not viable. This PR fixes the issues with the publication block to publish the *remapped* jar in intermediary. See the associated message in MMD for a slightly more detailed explanation [here](https://discord.com/channels/176780432371744769/821563191159029780/890677108140027924).
=> Use remapped jars for publishing to maven

src/main/java/software/bernie/geckolib3/renderers/geo/ExtendedGeoEntityRenderer.java
Fixes my implementation for armor scaling.
How it was: When the armor bone had a different size than the standard size it scaled (that was correct) but didn't move the bone coerrectly
How it is now: the armor will render at the correct place
=> fix armor at wrong position when bones have different sizes

src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
Since https://github.com/bernie-g/geckolib/commit/7b323eaa02755b9c64284767e77bf9b285c3902d GeckoLib creates a custom VertexMultiConsumer for rendering the geo entities 
https://github.com/bernie-g/geckolib/blob/72fec608030883058a4a7a18d462efc7d564fe02/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java#L161-L162
The consumer uses **_glintDirect_** and **_translucentCull_** render types buffers, but uses the MultiBufferSource passed on the method to get them.
Mods like CarryOn that want to render entities in their own way, pass incomplete buffer sources to render entities, those buffer sources might not contain the render types that GeckoLib wants to get, causing a default buffer to be returned, and thus throwing a IllegalArgumentException "Duplicate Delegate" when …
=> Fix GeoEntityRenderer render buffers

src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
While hovering over the entity, no matter of hiding the GUI the name tag was still showing.
=> [1.18 - Forge] fix(entity-nametag): Respect Minecraft.renderNames

src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
=> [1.19 - Forge] fix(entity-nametag): Respect Minecraft.renderNames

src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
=> [1.19 - Fabric] fix(entity-nametag): Respect Minecraft.renderNames

Fabric/src/main/java/software/bernie/example/ClientListener.java, Fabric/src/main/java/software/bernie/example/GeckoLibMod.java, Forge/src/main/java/software/bernie/example/ClientListener.java, Forge/src/main/java/software/bernie/example/GeckoLibMod.java, Quilt/src/main/java/software/bernie/example/ClientListener.java, Quilt/src/main/java/software/bernie/example/GeckoLibMod.java
Due to the arbitrary mod loading order on Fabric and Quilt, mods setting the `GeckolibMod.DISABLE_IN_DEV` field do not always have an effect, as they may be loaded after examples are already registered. Therefore, a system property should be added, which can be set through command line arguments and therefore always apply.
The PR adds the system property `geckolib.disable_examples`. When set to the string "true", registration of examples is disabled. This is added for all modloaders.
On Quilt and Fabric, `GeckolibMod.DISABLE_IN_DEV` is now deprecated.
The changes can be tested by creating a new run config, e.g. by putting this in the `loom` section of `build.gradle`:
```groovy
runs {
noExamples {
inherit client
name "No Examples"
vmArg "-Dgeckolib.disable_examples=true"
}
}
```
=> Add geckolib.disable_examples system property, deprecate GeckoLibMod.DISABLE_IN_DEV on Fabric/Quilt

Forge/src/main/java/software/bernie/geckolib3/geo/render/built/GeoBone.java, Forge/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java
This PR brings back the world position tracking for bones, and fixes the issues around it. It also adds method to get the local position of the bones.
To get the "_world position_" of a bone we calculate their local position first, and add to it the animatable position.
This is done by copying the matrix that the render dispatcher passed to us. At that point, the matrix **only** contains projection transforms about where (in the screen) our entity should be rendered, so by inverting and multiplying it we get rid of this, leaving a matrix pointing only to the entity transforms for our bone. Then the matrix gets translated to the animatable pos and that's all.
The old code to get the world pos (the one that got removed with https://github.com/bernie-g/geckolib/commit/8a55baf1f33333ba3618122e …
=> Reimplement GeoBone#getWorldPosition tracking

Forge/core/src/main/java/software/bernie/geckolib3/core/manager/AnimationFactory.java, Forge/core/src/main/java/software/bernie/geckolib3/core/manager/InstancedAnimationFactory.java, Forge/core/src/main/java/software/bernie/geckolib3/core/manager/SingletonAnimationFactory.java, Forge/src/main/java/software/bernie/example/block/tile/FertilizerTileEntity.java, Forge/src/main/java/software/bernie/example/block/tile/HabitatTileEntity.java, Forge/src/main/java/software/bernie/example/entity/BikeEntity.java, Forge/src/main/java/software/bernie/example/entity/CarEntity.java, Forge/src/main/java/software/bernie/example/entity/ExtendedRendererEntity.java, Forge/src/main/java/software/bernie/example/entity/GeoExampleEntity.java, Forge/src/main/java/software/bernie/example/entity/LEEntity.java, Forge/src/main/java/software/bernie/example/entity/ReplacedCreeperEntity.java, Forge/src/main/java/software/bernie/example/entity/TexturePerBoneTestEntity.java, Forge/src/main/java/software/bernie/example/item/GeckoArmorItem.java, Forge/src/main/java/software/bernie/example/item/JackInTheBoxItem.java, Forge/src/main/java/software/bernie/example/item/PistolItem.java, Forge/src/main/java/software/bernie/geckolib3/util/GeckoLibUtil.java
Should be non-breaking
Marked with deprecation and notes for future changes
Ideally devs would move to the new factory methods for the future, so that factories can properly retrieve AnimationData instances in an efficient manner
Additionally moved the data map to a fastutil unboxing-free map
=> AnimationFactory split

Forge/core/src/main/java/software/bernie/geckolib3/core/builder/ILoopType.java, Forge/src/main/java/software/bernie/geckolib3/util/json/JsonAnimationUtils.java
Move to a better/safer parsing for ILoopType from json
This should resolve https://github.com/bernie-g/geckolib/issues/316, but is also just better in general and should be done regardless
=> Move to a safer parser for ILoopType

Fabric/src/main/java/software/bernie/geckolib/model/GeoModel.java, Forge/src/main/java/software/bernie/geckolib/model/GeoModel.java, NeoForge/src/main/java/software/bernie/geckolib/model/GeoModel.java
This Pull Request aims to fix a animation/model jittering while using animatables with `GeoReplacedEntity`.
The following change has been made:
- Added `OR` statement for `GeoReplacedEntity` on `GeoModel#handleAnimations` to fix model/animations jittering due to a wrong currentFrameTime calculation being used.
Tested as working with the various example entities in-game and with a Custom Replaced Zombie Entity, no issues noticed.
=> fix: GeoReplaceEntity animation/model jittering.

common/src/main/java/software/bernie/geckolib/renderer/GeoItemRenderer.java
This PR modifies the GeoItemRenderer to set up lighting state before getting the VertexConsumer from the BufferSource. This allows other mods to access the correct lighting state when creating a VertexConsumer for rendering the item.
Helps to fix https://github.com/RaphiMC/ImmediatelyFast/issues/220
=> Set up lighting before getting VertexConsumer

forge/src/main/java/software/bernie/geckolib/network/GeckoLibNetworkingForge.java
This moves the networkProtocolVersion call before the optional call which allows Forge clients to connect to servers. 
The reason this needs to go first is because the optional call uses the default value for the network protocol version, which is 0, and then the following network protocol version doesn't update (or wipe) the previously assigned network acceptance tests.
Not sure if there's anything else to test to ensure this is working on Forge 1.20.6
=> Fix Forge compatibility

common/src/main/java/software/bernie/geckolib/mixin/client/HumanoidArmorLayerMixin.java
By ensuring that the handler uses the same stack as the target method, it ensures that when another mod makes changes to the stack returned by `getItemBySlot`, those changes are reflected in the stack passed to the geo renderer as the reference may have changed.
=> Avoid duplicating mc code to improve compat in mixins

Fabric/src/main/java/software/bernie/geckolib/mixins/fabric/MixinItemRenderer.java
Due to the nature of the WrapOperation, mods are unable to have their own WrapOperations run alongside GeckoLib's, due to GeckoLib not calling the original.
=> Fix items not rendering for other mods with a similar WrapOperation
